#!/usr/bin/env python

# GY170804

''' explode: split FASTA/Q records to new files '''


from __future__ import print_function  # Py2
from argparse import ArgumentParser, FileType, SUPPRESS
from collections import namedtuple
from itertools import cycle
from math import ceil
from os import path
from signal import signal, SIGPIPE, SIG_DFL
from string import ascii_letters, digits  # Py2
from sys import stdin, stdout


# Globals #####################################################################


signal(SIGPIPE, SIG_DFL)  # Gracefully handle downstream PIPE closure

# data structures
seqrecord = namedtuple('seqrecord', ['seqid', 'seq', 'quals'])

filenamechars = "-_" + ascii_letters + digits


# Classes #####################################################################


class MultiReader(object):
    ''' A class for reading FASTA/Q records '''

    def __init__(self, inputstream):
        self._fileobj = inputstream
        self._buffer = ' '

    def __enter__(self):
        return self

    def __exit__(self, type, value, traceback):
        pass

    def __iter__(self):
        return self

    def __next__(self):
        while self._buffer and self._buffer[0] not in ('>', '@'):
            self._buffer = self._fileobj.readline()
        if not self._buffer:
            raise StopIteration
        if self._buffer[0] == ">":
            seqid = self._buffer[1:].strip()
            self._buffer = self._fileobj.readline()
            seqlines = []
            while self._buffer and self._buffer[0] not in ('>', '@'):
                seqlines.append(self._buffer.strip())
                self._buffer = self._fileobj.readline()
            return seqrecord(seqid, ''.join(seqlines).upper(), '')
        else:
            seqid = self._buffer[1:].strip()
            seq = self._fileobj.readline().strip().upper()
            self._fileobj.readline()
            quals = self._fileobj.readline().strip()
            self._buffer = self._fileobj.readline()
            return seqrecord(seqid, seq, quals)

    next = __next__  # Py2 compatibility


# Functions ###################################################################


def grouper(iterable, k):
    ''' Yield a memory-mapped iterable in chunks of `k` '''
    for i in range(int(ceil(float(len(iterable)) / k))):  # Py2
        yield iterable[i*k:i*k+k]


def printseq(record, fileobj=stdout):
    ''' Appropraitely prints a seqrecord or equivalent 2 or 3-item iterable '''
    if len(record) == 3 and record[2]:
        print('@{}\n{}\n+\n{}'.format(*record), file=fileobj)
    elif 'wrap' not in args:
        print('>{}\n{}'.format(record[0], record[1]), file=fileobj)
    else:
        print('>{}'.format(record[0]), file=fileobj)
        for chunk in grouper(record[1], args.wrap):
            print(chunk, file=fileobj)


def sanitise(basename, sub='_'):
    ''' Substitute nasty characters in file names '''
    return ''.join(c if c in filenamechars else sub for c in basename)


###############################################################################


if __name__ == '__main__':

    parser = ArgumentParser(
        description='Split FASTA/Q records to new files',
        argument_default=SUPPRESS)
    parser.add_argument(
        'input', nargs='*', type=FileType('r'), default=[stdin],
        help='Input file(s) (use "-" or leave blank for stdin)')
    parser.add_argument(
        '-c', '--chunks', type=int,
        help='Split the file into `c` chunks')
    parser.add_argument(
        '-w', '--wrap', nargs='?', type=int, const=80,
        help='Wrap lines at `w` when outputting FASTA (default %(const)s \
        when supplied alone)')
    parser.add_argument(
        '--dir', default='',
        help='Output to an existing directory, `dir`')
    parser.add_argument(
        '--prefix', default='',
        help='Preceed seqid, or chunk number with `-c`, with `prefix`')

    args = parser.parse_args()

    if 'chunks' not in args:
        for f in args.input:
            with MultiReader(f) as F:
                for record in F:
                    n = sanitise(record.seqid.split(' ')[0])
                    n = path.join(args.dir, args.prefix + n + \
                        '.fq' if record.quals else '.fa')
                    with open(n, 'w') as outfile:
                        printseq(record, outfile)

    else:
        outfs = [open(path.join(args.dir, args.prefix + '{}'.format(i)), 'w')
            for i in range(1, args.chunks + 1)]
        outfsloop = cycle(outfs)
        for f in args.input:
            with MultiReader(f) as F:
                for record in F:
                    printseq(record, next(outfsloop))
        for f in outfs:
            f.close()
