#!/usr/bin/env bash

version="GY170731"
usage="\
interleave ($version): interleaving FASTQ data
interleave [-h] <in1> <in2>"

while getopts :h option; do
    case "$option" in
        h)
            echo "$usage"
            exit
            ;;
        \?)
            echo "$usage"
            exit 1
            ;;
    esac
done

if (( $# == 2 )) ; then
    paste <(cat $1 | paste - - - -) <(cat $2 | paste - - - -) | tr "\t" "\n"
else
    echo "$usage"
    exit 1
fi
