#!/usr/bin/env bash

version="GY170731"
usage="\
interleave ($version): interleaving FASTQ data
interleave [-h] <in1> <in2>"

while getopts :h option; do
    case "$option" in
        h)
            echo "$usage"
            exit
            ;;
        \?)
            echo "$usage"
            exit 1
            ;;
    esac
done

if (( $# == 2 )) ; then
    paste $1 $2 \
    | paste - - - - | \
    awk 'BEGIN {FS="\t";OFS="\n"} {print $1,$3,$5,$7,$2,$4,$6,$8}'
else
    echo "$usage"
    exit 1
fi
